# Generated by Django 3.0.6 on 2021-12-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iot_car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=15)),
                ('fluid_level', models.CharField(choices=[('LOW', 'LOW'), ('HALF', 'HALF'), ('FULL', 'FULL')], max_length=4)),
                ('engine_temp', models.IntegerField()),
                ('tire_pressure', models.IntegerField()),
                ('loc_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('loc_lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Iot_frodge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=15)),
                ('ice_level', models.CharField(choices=[('LOW', 'LOW'), ('HALF', 'HALF'), ('FULL', 'FULL')], max_length=4)),
                ('wate_leak', models.BooleanField()),
                ('loc_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('loc_lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
    ]
