# Generated by Django 3.2.10 on 2021-12-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IotCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=15)),
                ('fluid_level', models.CharField(choices=[('LOW', 'LOW'), ('HALF', 'HALF'), ('FULL', 'FULL')], max_length=4)),
                ('engine_temp', models.IntegerField()),
                ('tire_pressure', models.IntegerField()),
                ('loc_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('loc_lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='IotFridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=15)),
                ('ice_level', models.CharField(choices=[('LOW', 'LOW'), ('HALF', 'HALF'), ('FULL', 'FULL')], max_length=4)),
                ('wate_leak', models.BooleanField()),
                ('loc_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('loc_lng', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.DeleteModel(
            name='Iot_car',
        ),
        migrations.DeleteModel(
            name='Iot_frodge',
        ),
    ]
