# Generated by Django 3.2.10 on 2021-12-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_api', '0003_rename_wate_leak_iotfridge_water_leak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iotfridge',
            name='water_leak',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=4),
        ),
    ]
