# Generated by Django 3.2.10 on 2021-12-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme_api', '0004_alter_iotfridge_water_leak'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iotcar',
            old_name='make',
            new_name='track_id',
        ),
        migrations.RenameField(
            model_name='iotfridge',
            old_name='make',
            new_name='track_id',
        ),
    ]
