# Generated by Django 3.2.10 on 2021-12-21 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acme_api', '0005_auto_20211221_0003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IotCar',
            new_name='Car',
        ),
        migrations.RenameModel(
            old_name='IotFridge',
            new_name='Fridge',
        ),
    ]
