# Generated by Django 3.2.10 on 2021-12-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_api', '0006_auto_20211221_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='track_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='track_id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
