# Generated by Django 3.2.10 on 2021-12-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_api', '0007_auto_20211222_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='device_type',
            field=models.CharField(choices=[('CAR', 'CAR'), ('FRIDGE', 'FRIDGE'), ('UNKOWN', 'UNKOWN')], default='UNKOWN', max_length=15),
        ),
        migrations.AddField(
            model_name='fridge',
            name='device_type',
            field=models.CharField(choices=[('CAR', 'CAR'), ('FRIDGE', 'FRIDGE'), ('UNKOWN', 'UNKOWN')], default='UNKOWN', max_length=15),
        ),
        migrations.AlterField(
            model_name='car',
            name='fluid_level',
            field=models.CharField(choices=[('LOW', 'LOW'), ('HALF', 'HALF'), ('FULL', 'FULL')], default='FULL', max_length=4),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='ice_level',
            field=models.CharField(choices=[('LOW', 'LOW'), ('HALF', 'HALF'), ('FULL', 'FULL')], default='FULL', max_length=4),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='water_leak',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=4),
        ),
    ]
