# Generated by Django 3.2.10 on 2021-12-22 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acme_api', '0008_auto_20211222_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basic_device',
            fields=[
                ('track_id', models.AutoField(primary_key=True, serialize=False)),
                ('loc_lat', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('loc_lng', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('device_type', models.CharField(choices=[('CAR', 'CAR'), ('FRIDGE', 'FRIDGE'), ('UNKOWN', 'UNKOWN')], default='UNKOWN', max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='loc_lat',
        ),
        migrations.RemoveField(
            model_name='car',
            name='loc_lng',
        ),
        migrations.RemoveField(
            model_name='car',
            name='track_id',
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='loc_lat',
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='loc_lng',
        ),
        migrations.RemoveField(
            model_name='fridge',
            name='track_id',
        ),
        migrations.AddField(
            model_name='car',
            name='basic_device_ptr',
            field=models.OneToOneField(auto_created=True, default=1234567890, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='acme_api.basic_device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fridge',
            name='basic_device_ptr',
            field=models.OneToOneField(auto_created=True, default=1234567890, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='acme_api.basic_device'),
            preserve_default=False,
        ),
    ]
