# Generated by Django 3.2.10 on 2021-12-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_api', '0009_auto_20211222_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fluid_level',
            field=models.CharField(choices=[('LOW', 'LOW'), ('HALF', 'HALF'), ('FULL', 'FULL')], max_length=4),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='ice_level',
            field=models.CharField(choices=[('LOW', 'LOW'), ('HALF', 'HALF'), ('FULL', 'FULL')], max_length=4),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='water_leak',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=4),
        ),
    ]
